spring:
  jpa:
    properties.hibernate.hbm2ddl.auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
datasource:
  products:
    url: jdbc:h2:mem:products
    username: sa
    password: