spring:
  jpa:
    properties.hibernate.hbm2ddl.auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
datasource:
  products:
    url: jdbc:h2:mem:transactions
    username: sa
    password: